version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - gateway

  ntcore:
    image: "ntcore/webserver:latest"
    container_name: "ntcore-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntcore.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ntcore.entrypoints=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - data:/usr/src/app/data
      - "./app-config/ntcore.yml:/usr/src/app/app-config/ntcore.yml"
    networks:
      - gateway
    depends_on:
      - timescaleDB

  timescaleDB:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  gateway:
    driver: bridge

volumes:
  data: