---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ntcore
  region: cn-northwest-1

nodeGroups:
  - name: beta
    instanceType: t3.medium
    desiredCapacity: 1
    iam:
      attachPolicyARNs:
        - arn:aws-cn:iam::aws:policy/CloudWatchFullAccess
        - arn:aws-cn:iam::aws:policy/AmazonKinesisFullAccess
        - arn:aws-cn:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws-cn:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws-cn:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws-cn:iam::aws:policy/AmazonS3FullAccess