---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ntcore
  region: cn-northwest-1

nodeGroups:
  - name: beta
    instanceType: t3.medium
    desiredCapacity: 1
    iam:
      attachPolicyARNs:
        - arn:aws-cn:iam::aws:policy/CloudWatchFullAccess