---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ntcore-service-role
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - create
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
    verbs:
      - get
      - list
      - create
      - update

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ntcore-service-role
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: ntcore-service-role
  apiGroup: ""