---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ntcore-monitoring
data:
  monitoring.yml: |
    monitoring:
      provider:
        type: cloudwatch
        config: 
          region: us-east-1
    logging:
      provider:
        type: cloudwatch
        group: /ntcore/monitoring/dev
        config: 
          region: 'us-east-1'
          accessKeyId:
          secretAccessKey:
      streamProvider:
        type: kinesis
        name: log-event-stream-dev
        config:
          region: 'cn-northwest-1'
          accessKeyId:
          secretAccessKey:
    database:
      provider:
        type: dynamodb
        config:
          region: us-east-1

---
apiVersion: v1
kind: Service
metadata:
  name: ntcore-monitoring
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 8180
      targetPort: 8180
  selector:
    app: ntcore-monitoring

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ntcore-monitoring
  labels:
    app: ntcore-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntcore-monitoring
  template:
    metadata:
      labels:
        app: ntcore-monitoring
    spec:
      volumes:
        - name: ntcore-monitoring
          configMap:
            name: ntcore-monitoring
      containers:
        - name: ntcore-monitoring
          image: ntcore/monitoring:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8180
          volumeMounts:
            - name: ntcore-monitoring
              mountPath: /usr/src/app/app-config
          env:
            - name: AWS_ACCESS_KEY_ID
              value: AKIAQ2AR72HWDJD4BZQ3
            - name: AWS_SECRET_ACCESS_KEY
              value: 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

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ntcore-monitoring
spec:
  rules:
  - http:
      paths:
      - path: /dsp/console/monitoring
        pathType: Prefix
        backend:
          service:
            name: ntcore-monitoring
            port:
              number: 8180
      - path: /dsp/monitoring
        pathType: Prefix
        backend:
          service:
            name: ntcore-monitoring
            port:
              number: 8180

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: https://$host/dsp/api/v1/users/authorize
    nginx.ingress.kubernetes.io/auth-response-headers: X-NTCore-Auth-User
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ntcore-monitoring-api
spec:
  rules:
  - http:
      paths:
      - path: /dsp/api/v[0-9]+/monitoring
        pathType: Prefix
        backend:
          service:
            name: ntcore-monitoring
            port:
              number: 8180