---
apiVersion: v1
kind: Service
metadata:
  name: ntcore
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 8180
      targetPort: 8180
  selector:
    app: ntcore

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ntcore
  labels:
    app: ntcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntcore
  template:
    metadata:
      labels:
        app: ntcore
    spec:
      volumes:
        - name: ntcore-global
          configMap:
            name: ntcore-global
        - name: ntcore-kubernetes
          configMap:
            name: ntcore-kubernetes
      containers:
        - name: ntcore
          image: ntcore/webserver:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8180
          volumeMounts:
            - name: ntcore-global
              mountPath: /usr/src/app/app-config/global
            - name: ntcore-kubernetes
              mountPath: /usr/src/app/app-config/kubernetes
          env:
            - name: AWS_ACCESS_KEY_ID
              value: AKIAQ2AR72HWDJD4BZQ3
            - name: AWS_SECRET_ACCESS_KEY
              value: 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

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ntcore
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ntcore
            port:
              number: 8180
      - path: /dsp/console
        pathType: Prefix
        backend:
          service:
            name: ntcore
            port:
              number: 8180
      - path: /dsp/public
        pathType: Prefix
        backend:
          service:
            name: ntcore
            port:
              number: 8180

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: https://$host/dsp/api/v1/users/authorize
    nginx.ingress.kubernetes.io/auth-response-headers: X-NTCore-Auth-User
    nginx.ingress.kubernetes.io/proxy-body-size: "5000m"
  name: ntcore-api
spec:
  rules:
  - http:
      paths:
      - path: /dsp/api
        pathType: Prefix
        backend:
          service:
            name: ntcore
            port:
              number: 8180